---
#----Deployment----
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loyalty-deployment
  labels: 
    app: loyalty
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loyalty
  template:
    metadata:
      labels:
        app: loyalty
    spec:
      containers:
        - name: loyalty
          image: s21laneryel/loyalty-service:v2.0
          ports:
            - containerPort: 8085
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: postgres-username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: postgres-password
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: app-configmap
                  key: postgres-host
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  name: app-configmap
                  key: postgres-port 
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: app-configmap
                  key: postgres-balances-db

---
#----Service----
apiVersion: v1
kind: Service
metadata:
  name: loyalty-service 
spec:
  selector:
    app: loyalty
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 8085