apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
data:
  #postgres
  postgres-username: cG9zdGdyZXM=       #postgres
  postgres-password: cG9zdGdyZXM=       #postgres

  #rabbitmq
  rabbitmq-username: Z3Vlc3Q=           #guest
  rabbitmq-password: Z3Vlc3Q=           #guest
  rabbit-queue: bWVzc2FnZXF1ZXVl
  rabbit-exchange: bWVzc2FnZXF1ZXVlLWV4Y2hhbmdl

  #api_publicKey
  publicKey: TUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUF2VU5ZWmVxTExBb09VNitOeUZ0S1wKY2RsczlMUXppa1I1M0szbVhIc054dnV0MExsNnkwbStRVVlkdUt0SG8rRnZsby9QK2tVZXI4QnRZUmJUeUFhc1wKdWptRkx4SFFaam1zdlhoS2MwSE5sOHR1ZDZra01zWEtPQlpzalN3TUg4cE5DVXVReW5Xb0Urbkxkd0trSHZmcVwKQnJCQjM5ZkFsZy8zWjJLM3lpT3VPTHFwNGlOeTg2NVBtSnlNR2ZBUW9TakRlTktuZTE1RWJsckNRUmhDYS9vYVwKZFJkU3IybUd6OC80S3J3U1V2aUpSdCsvK3BqdGNhREdnM3o4UkZBaVd4NGxrdkQzRW5ndlU1WlZWYlF2cU1qNVwKME0yQkd3WWUyWDhXOEFBOTh1UlZ0NnNWamQ5N0VPZDEyaCs4eDZKM1RBRUNlb1VFVGdtK2pKZjlHd1NuMU5JY1wKL1FJREFRQUI=
